services:
  app:
    build: .
    container_name: combined_container
    ports:
      - "${PORT}:80"
    volumes:
      - ./project:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    
